Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [25]:
from sklearn.datasets import load_iris
import numpy as np 

data = load_iris()

x = data.data   
y = data.target 

mean = np.mean(x,axis=0)
median = np.median(x,axis=0)
sd = np.std(x,axis=0)

print("mean : ",mean)
print("median : ",median)
print("standard deviation : ",sd)

variance = np.var(x,axis=0)

index = np.argmax(sd)
feature_names = data.feature_names
print("Highest variability : ",feature_names[index])


new_shpe = x[:,0] 
print(new_shpe.shape)
new_shpe = new_shpe.reshape(2,-1)
print(new_shpe.shape)

mean :  [5.84333333 3.05733333 3.758      1.19933333]
median :  [5.8  3.   4.35 1.3 ]
standard deviation :  [0.82530129 0.43441097 1.75940407 0.75969263]
Highest variability :  petal length (cm)
(150,)
(2, 75)

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [29]:
from sklearn.datasets import load_iris
import numpy as np 

data = load_iris()
x = data.data

last_two = x[0:100,:-2]

print(last_two)

mask = x[:,2] > np.mean(x[:,2],axis=0)

x = x[mask]

print("size after filtering: ",x.shape[0])

[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [5.  3.4]
 [4.4 2.9]
 [4.9 3.1]
 [5.4 3.7]
 [4.8 3.4]
 [4.8 3. ]
 [4.3 3. ]
 [5.8 4. ]
 [5.7 4.4]
 [5.4 3.9]
 [5.1 3.5]
 [5.7 3.8]
 [5.1 3.8]
 [5.4 3.4]
 [5.1 3.7]
 [4.6 3.6]
 [5.1 3.3]
 [4.8 3.4]
 [5.  3. ]
 [5.  3.4]
 [5.2 3.5]
 [5.2 3.4]
 [4.7 3.2]
 [4.8 3.1]
 [5.4 3.4]
 [5.2 4.1]
 [5.5 4.2]
 [4.9 3.1]
 [5.  3.2]
 [5.5 3.5]
 [4.9 3.6]
 [4.4 3. ]
 [5.1 3.4]
 [5.  3.5]
 [4.5 2.3]
 [4.4 3.2]
 [5.  3.5]
 [5.1 3.8]
 [4.8 3. ]
 [5.1 3.8]
 [4.6 3.2]
 [5.3 3.7]
 [5.  3.3]
 [7.  3.2]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [4.9 2.4]
 [6.6 2.9]
 [5.2 2.7]
 [5.  2. ]
 [5.9 3. ]
 [6.  2.2]
 [6.1 2.9]
 [5.6 2.9]
 [6.7 3.1]
 [5.6 3. ]
 [5.8 2.7]
 [6.2 2.2]
 [5.6 2.5]
 [5.9 3.2]
 [6.1 2.8]
 [6.3 2.5]
 [6.1 2.8]
 [6.4 2.9]
 [6.6 3. ]
 [6.8 2.8]
 [6.7 3. ]
 [6.  2.9]
 [5.7 2.6]
 [5.5 2.4]
 [5.5 2.4]
 [5.8 2.7]
 [6.  2.7]
 [5.4 3. ]
 [6.  3.4]
 [6.7 3.1]
 [6.3 2.3]
 [5.6 3. ]
 [5.5 2.5]
 [5.5 2.6]
 [6.1 3. ]
 [5.8 2.6]
 [5.  2.3]
 [5.6 2.7]
 [5.7 3. ]
 [5.7 2.9]
 [6.2 2.9]
 [5.1 2.5]
 [5.7 2.8]]
size after filtering:  93

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [34]:
import seaborn as sns 
import pandas as pd


df = sns.load_dataset("titanic")

print("Head")
print(df.head())

print("Tail")
print(df.tail())

print("Info")
print(df.info())

Head
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
Tail
     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second
887         1       1  female  19.0      0      0  30.00        S   First
888         0       3  female   NaN      1      2  23.45        S   Third
889         1       1    male  26.0      0      0  30.00        C   First
890         0       3    male  32.0      0      0   7.75        Q   Third

       who  adult_male deck  embark_town alive  alone
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True
Info
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
None

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [43]:
import seaborn as sns 
import pandas as pd


df = sns.load_dataset("titanic")

female = df[(df['sex'] == 'female') & (df['class'] == 'First')]

female
print("Survival rate : ", female['survived'].mean()*100)

print("Overall survival rate : ",df['survived'].mean()*100)

Survival rate :  96.80851063829788
Overall survival rate :  38.38383838383838

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [51]:
import seaborn as sns 
import pandas as pd


df = sns.load_dataset("titanic")

df['age'] = df['age'].fillna(df['age'].median())


df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])


df = df.drop(columns=['deck'])


print(df.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [58]:
import seaborn as sns 
import pandas as pd


df = sns.load_dataset("titanic")

df['family_size'] = df['sibsp'] + df['parch'] + 1 


df['is_alone'] = (~(df['alone']==True)).astype(int)

df['is_alone'].groupby(df['survived']).agg('mean')

survived
0    0.318761
1    0.523392
Name: is_alone, dtype: float64

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [77]:
import seaborn as sns
import pandas as pd 

df = sns.load_dataset("tips")



df['tip_percentage'] = df['tip']/df['total_bill']*100

df.groupby('day')['tip'].mean()

avg_tips = df.groupby('day')['tip'].mean()

print("Highest tipping day : ",avg_tips.idxmax())

Highest tipping day :  Sun

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [82]:
import seaborn as sns
import pandas as pd 

df = sns.load_dataset("tips")

df = df[(df['total_bill']>20) & (df['tip']<3)]

df = df.drop(columns=['size'])

df

     total_bill   tip     sex smoker   day    time
21        20.29  2.75  Female     No   Sat  Dinner
33        20.69  2.45  Female     No   Sat  Dinner
48        28.55  2.05    Male     No   Sun  Dinner
57        26.41  1.50  Female     No   Sat  Dinner
68        20.23  2.01    Male     No   Sat  Dinner
102       44.30  2.50  Female    Yes   Sat  Dinner
113       23.95  2.55    Male     No   Sun  Dinner
119       24.08  2.92  Female     No  Thur   Lunch
129       22.82  2.18    Male     No  Thur   Lunch
131       20.27  2.83  Female     No  Thur   Lunch
153       24.55  2.00    Male     No   Sun  Dinner
166       20.76  2.24    Male     No   Sun  Dinner
187       30.46  2.00    Male    Yes   Sun  Dinner
192       28.44  2.56    Male    Yes  Thur   Lunch
208       24.27  2.03    Male    Yes   Sat  Dinner
210       30.06  2.00    Male    Yes   Sat  Dinner
229       22.12  2.88  Female    Yes   Sat  Dinner
230       24.01  2.00    Male    Yes   Sat  Dinner
237       32.83  1.17    Male    Yes   Sat  Dinner
240       27.18  2.00  Female    Yes   Sat  Dinner
241       22.67  2.00    Male    Yes   Sat  Dinner

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [94]:
import numpy as np

a = np.arange(6).reshape(3, 2)
b = np.arange(10, 16).reshape(3, 2)

result = np.vstack((a,b))

result = result.reshape(2,6)
print(result)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]]

Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [114]:
import seaborn as sns 
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = sns.load_dataset("titanic")

missing_count = df.isna().sum()

total_cells = np.prod(df.shape)

total_missing_cells = missing_count.sum()/total_cells*100

print(total_missing_cells)


df.isnull().sum()

df['age'] = df['age'].fillna(df['age'].mean)

df = df.dropna()

df.isnull().sum()


df = pd.get_dummies(df,columns=['sex','embarked'],drop_first=True)

numerical_features = df.select_dtypes(include='number').columns

print(numerical_features)

scaler = MinMaxScaler()

df[numerical_features] = scaler.fit_transform(df[numerical_features])

df

6.502057613168724
Index(['survived', 'pclass', 'sibsp', 'parch', 'fare'], dtype='str')

,survived,pclass,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,sex_male,embarked_Q,embarked_S
1,1.0,0.0,38.0,0.333333,0.00,0.139136,First,woman,False,C,Cherbourg,yes,False,False,False,False
3,1.0,0.0,35.0,0.333333,0.00,0.103644,First,woman,False,C,Southampton,yes,False,False,False,True
6,0.0,0.0,54.0,0.000000,0.00,0.101229,First,man,True,E,Southampton,no,True,True,False,True
10,1.0,1.0,4.0,0.333333,0.25,0.032596,Third,child,False,G,Southampton,yes,False,False,False,True
11,1.0,0.0,58.0,0.000000,0.00,0.051822,First,woman,False,C,Southampton,yes,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1.0,0.0,47.0,0.333333,0.25,0.102579,First,woman,False,D,Southampton,yes,False,False,False,True
872,0.0,0.0,33.0,0.000000,0.00,0.009759,First,man,True,B,Southampton,no,True,True,False,True
879,1.0,0.0,56.0,0.000000,0.25,0.162314,First,woman,False,C,Cherbourg,yes,False,False,False,False
887,1.0,0.0,19.0,0.000000,0.00,0.058556,First,woman,False,B,Southampton,yes,True,False,False,True
889,1.0,0.0,26.0,0.000000,0.00,0.058556,First,man,True,C,Cherbourg,yes,True,True,False,False

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [122]:
from sklearn.datasets import load_iris
import numpy as np 
import pandas as pd 


data = load_iris(as_frame=True)

df = data.frame

corr_matrix = df.corr(numeric_only=True)

print(corr_matrix)

threshold = 0.8 

upper  = corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(bool))

high_corr_features = [col for col in upper.columns if any(upper[col])>threshold]

df = df.drop(columns=high_corr_features)

df

                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754
sepal width (cm)           -0.117570          1.000000          -0.428440
petal length (cm)           0.871754         -0.428440           1.000000
petal width (cm)            0.817941         -0.366126           0.962865
target                      0.782561         -0.426658           0.949035

                   petal width (cm)    target
sepal length (cm)          0.817941  0.782561
sepal width (cm)          -0.366126 -0.426658
petal length (cm)          0.962865  0.949035
petal width (cm)           1.000000  0.956547
target                     0.956547  1.000000

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[150 rows x 0 columns]

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [128]:
import seaborn as sns 
import pandas as pd 
import numpy as np 


df = sns.load_dataset("titanic")

df['age_group'] = pd.cut(df['age'],
    bins=[0, 18, 60, 100],
    labels=['child', 'adult', 'senior'])

survive_rate_per_group = df.groupby(df['age_group'])['survived'].agg('mean')

print("Highest survivability : ",survive_rate_per_group.idxmax())

Highest survivability :  child

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [129]:
import numpy as np

errors = np.random.randn(1000)

mean = np.mean(errors)
std = np.std(errors)

lower = mean - 2 * std
upper = mean + 2 * std

outliers = errors[(errors < lower) | (errors > upper)]

print(mean)
print(std)
print(outliers)

-0.0016085279065783382
0.9989150436725762
[ 2.26085743 -2.07093247 -2.02111524  2.85690097 -2.87809597 -2.27529437
  2.49975894  2.09863009 -3.01855926 -2.15356421  2.48137862  2.14797842
  2.23033883 -2.75340462 -2.16044277 -2.03682426 -2.09111114 -3.02303489
 -2.87922555 -2.13062655  2.10228771  2.55077555  2.05724387  2.17450009
  2.06879013 -2.1502685   2.01890982  2.08563544  1.99743811 -1.99966648
 -3.24522603  2.12566493 -2.02867565  2.85294383 -2.39685136 -2.38128146
 -2.10608338  2.00757146  2.26526264  2.76472831 -2.4385001  -2.61869745
 -2.37096589  2.36424555]

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [130]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset("tips")

df['tip_percentage'] = (df['tip'] / df['total_bill']) * 100

grouped = df.groupby(['day', 'time']).agg({
    'total_bill': 'sum',
    'tip_percentage': 'mean'
}).reset_index()

highest_revenue = grouped.loc[grouped['total_bill'].idxmax()]

print(grouped)
print(highest_revenue)

    day    time  total_bill  tip_percentage
0  Thur   Lunch     1077.55       16.130074
1  Thur  Dinner       18.78       15.974441
2   Fri   Lunch       89.92       18.876489
3   Fri  Dinner      235.96       15.891611
4   Sat  Dinner     1778.40       15.315172
5   Sun  Dinner     1627.16       16.689729
day                     Sat
time                 Dinner
total_bill           1778.4
tip_percentage    15.315172
Name: 4, dtype: object